services:
  cverify-public:
    image: php:8.2-apache
    container_name: cverify-public
    user: root
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - user-data:/var/www/html/user/data
      - company-data:/var/www/html/company/data
    environment:
      - PHP_DISPLAY_ERRORS=Off
      - PHP_LOG_ERRORS=On
      - RELAY_SERVER_URL=http://cverify.cv:7070
    restart: unless-stopped

volumes:
  user-data:
    driver: local
  company-data:
    driver: local
